"""created the images database

Revision ID: 5762798d00ba
Revises: 
Create Date: 2019-11-11 18:17:25.821048

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5762798d00ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageDB',
                    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('image_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('_id')
                    )
    op.create_index(op.f('ix_imageDB__id'), 'imageDB', ['_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imageDB__id'), table_name='imageDB')
    op.drop_table('imageDB')
    # ### end Alembic commands ###
